#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/science?serverTimezone=GMT%2B8&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: fuck3148481
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#日志 开发用
logging:
  level:
    com:
      longder: DEBUG

#访问端口
server:
  port: 5188